// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmXm0xN1EWxgQMXzESDgLzPxMXPx_OFjA',
    appId: '1:166769308547:web:0280f1316be33e08e7bcb6',
    messagingSenderId: '166769308547',
    projectId: 'happysoul-bb5a3',
    authDomain: 'happysoul-bb5a3.firebaseapp.com',
    storageBucket: 'happysoul-bb5a3.appspot.com',
    measurementId: 'G-YZQVHD1QLK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJ7Bo3VM62YvT3PFWsb0yXajB8qqEnrXs',
    appId: '1:166769308547:android:f3e79a60570a4c45e7bcb6',
    messagingSenderId: '166769308547',
    projectId: 'happysoul-bb5a3',
    storageBucket: 'happysoul-bb5a3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXs5J-uYq7Cw3ytDfRFedA9ELuDh2rAVY',
    appId: '1:1073232410548:ios:49081cbeee04343899e4e1',
    messagingSenderId: '1073232410548',
    projectId: 'happysoul-b4f2e',
    storageBucket: 'happysoul-b4f2e.appspot.com',
    iosBundleId: 'com.example.happySoul',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXs5J-uYq7Cw3ytDfRFedA9ELuDh2rAVY',
    appId: '1:1073232410548:ios:1789959ae02b65d699e4e1',
    messagingSenderId: '1073232410548',
    projectId: 'happysoul-b4f2e',
    storageBucket: 'happysoul-b4f2e.appspot.com',
    iosBundleId: 'com.example.happySoul.RunnerTests',
  );
}